# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "44df4ce71b8e945a00cfe8e616bb7329"
name = "checkout-extensions"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
